# Generated by Django 5.1.6 on 2025-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_event_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed_to_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/avatar_placeholder.png', help_text='Upload a profile picture for the user.', null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
    ]
