# Generated by Django 5.2.3 on 2025-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_synced',
            field=models.BooleanField(default=False, help_text='Whether this event is synced to external calendar', verbose_name='Synced to Calendar'),
        ),
        migrations.AddField(
            model_name='event',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='ID of the event in Google Calendar', max_length=255, null=True, verbose_name='Google Calendar Event ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether reminder has been sent for this event', verbose_name='Reminder Sent'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_time',
            field=models.CharField(choices=[('none', 'No Reminder'), ('15min', '15 minutes before'), ('1hour', '1 hour before'), ('1day', '1 day before'), ('1week', '1 week before')], default='1day', help_text='When to send reminder before event', max_length=10, verbose_name='Reminder Time'),
        ),
    ]
